version: "3.9"
services:
  zookeeper_try:
    image: wurstmeister/zookeeper
    container_name: zookeeper_try
    ports:
      - "2181:2181"
  kafka_try:
    image: wurstmeister/kafka
    container_name: kafka_try
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_try:2181